theme: minima
title: Personal Blog
description: This is where I share cool stuff about my life
author: Your Name
# baseurl: "/blog2"
baseurl: "/blog2" # the subpath of your site, e.g. /blog
url: "https://dis-525.github.io" # the base hostname & protocol for your site





